.github/workflows/build.yml, jupyterhub_config.py
Fixes #12.
Simple GitHub Actions workflow to install and lint the plugin on different versions of Python.
=> Add Python workflow to install the plugin

README.md
=> Add CI Badge to the README

README.md
Add badge and link to Read the Docs.
=> Add link to the documentation to the README

.github/pull_request_template.md
To (hopefully) make it less likely to forget about the documentation.
=> Add a PR template to be reminded to update the doc

README.md
Move the logo a bit higher in the README file, so it looks nicer.
=> Move logo higher in the README

docs/install/requirements.rst
=> Add a reference to TLJH docs to create servers

docs/install/ansible.rst
- Fix issue #29
- Homogenize YAML file extension: .yaml -> .yml
=> Use local hosts file with ansible-playbook

docs/install/https.rst, docs/install/index.rst
=> Move the HTTPS section before Ansible

docs/requirements.txt
This PyData Sphinx theme is now available on PyPI.
=> Install pydata-sphinx-theme from pip

README.md
Remove the Requirements section from the README since it is part of the docs.
=> Remove Requirements section from the README

docs/install/ansible.rst
=> Fix small typo in conda env name

ansible/all.yml, ansible/utils.yml, docs/install/ansible.rst
=> Add extra utils packages

docs/configuration/resources.rst
=> Update documentation to mention nbresuse

jupyterhub_config.py
=> Fix config to test locally

ansible/uninstall.yml, docs/install/index.rst, docs/install/uninstall.rst
=> Add playbook to uninstall TLJH

docs/configuration/persistence.rst, docs/install/ansible.rst, docs/install/index.rst, docs/install/upgrade.rst
=> Add documentation about upgrading and backups

docs/install/requirements.rst
=> Add documentation for the local SSH config

tljh-plasmabio/tljh_plasmabio/builder.py
Fixes the following `TODO`: https://github.com/plasmabio/plasmabio/blob/0b82543857941044470736eb68bc434bac318baf/tljh-plasmabio/tljh_plasmabio/builder.py#L114
=> Run docker images build endpoints on an executor

ansible/https.yml, ansible/vars/default.yml, docs/configuration/persistence.rst, docs/install/https.rst
=> Set DNS and email in the hosts file

ansible/admins.yml, ansible/cockpit.yml
A quick Ansible playbook fix after trying the whole setup on a new machine.
=> Fix typos in https and admin playbooks

ansible/docker.yml, ansible/tljh.yml, docs/install/ansible.rst
=> Remove aptitude from Ansible playbooks

jupyterhub_config.py, tljh-plasmabio/tljh_plasmabio/__init__.py
A quick naming fix to be more explicit on what `base_path` refers to.
=> Rename base_path to base_volume_path

tljh-plasma/tljh_plasma/templates/page.html
Depends on https://github.com/plasmabio/tljh-repo2docker/pull/19
=> Update to the latest tljh-repo2docker

CHANGELOG.md, tljh-plasma/setup.py
Fixes #160. 
This will make it easier to track new features, bug fixes and other changes.
=> Add CHANGELOG.md

ansible/include-groups.yml, ansible/users.yml, docs/install/users.rst, docs/permissions/groups.rst
=> Create groups prior to user creation

docs/index.rst
=> Add a summary of the project in the doc

.gitignore
I have several `hosts*` files that I would like git ignore.
=> Ignore all hosts files

docs/contributing/local.rst
=> Fix typo in contributing doc

ansible/users.yml
=> Add option to not reset user password

docs/troubleshooting/index.rst
Fixes https://github.com/plasmabio/plasma/issues/195
=> Add documentation to access the logs of repo2docker

docs/troubleshooting/index.md
Fixes #194 
This PR consolidates the docs about the looking at logs:
=> Consolidate the logs section in the documentation

ansible/students-create.yml, ansible/students-remove.yml, docs/configuration/batch-users.md, docs/configuration/index.md, docs/install/users.md
=> Create and delete multiple student users

ansible/daemon.json, ansible/docker.yml, docs/troubleshooting/index.md
Fixes https://github.com/plasmabio/plasma/issues/204
Might help troubleshoot #191.
https://plasmabio--205.org.readthedocs.build/en/205/troubleshooting/index.html#looking-at-logs
=> Enable the journald logging driver

.gitignore, docs/configuration/batch-users.md, docs/configuration/resources.md
=> Update resource monitoring in documentation

.gitignore, docs/configuration/batch-users.md
=> Add batch remove in doc

ansible/tljh.yml, ansible/vars/default.yml, dev-requirements.txt
=> Switch tljh-repo2docker installer from git to pypi
