plasmabio/plasma

docs/install/ansible.rst
=> Add note about Ansible to the docs

ansible/all.yml, ansible/images.yml, ansible/tljh.yml, ansible/users.yml, docs/conf.py, docs/configuration/environments.rst, docs/configuration/index.rst, docs/configuration/persistence.rst, docs/requirements.txt, jupyterhub_config.py, tljh-plasmabio/setup.py, tljh-plasmabio/tljh_plasmabio/__init__.py, tljh-plasmabio/tljh_plasmabio/build_images.py
FIxes #25. 
Add `jupyter-repo2docker` to build the user images on the server.
=> Add jupyter-repo2docker

ansible/tljh.yml, docs/configuration/cull.rst, docs/configuration/index.rst
=> Cull servers after 1 hour of inactivity

.gitignore, ansible/hosts, docs/install/ansible.rst, docs/install/https.rst
Fixes #31.
Users are responsible for creating their own `hosts` file.
=> Remove the default hosts file

ansible/tljh.yml, docs/install/https.rst
Fixes #76.
This explicit task makes it possible to disable HTTPS, but the `--no-https` has to be explicitely provided:
```bash
ansible-playbook -i hosts all.yml -u ubuntu --tags "all,no-https"
```
=> Add an opt-in Ansible task to disable HTTPS

tljh-plasmabio/tljh_plasmabio/__init__.py
It turns out that the TLJH cull service was not enabled because the Plasmabio plugin would overwrite the list of services by assigning with `=`.
=> Add the environment service to the list of services

ansible/tljh.yml
The `tljh-config reload` command used in the playbook would only reload the hub by default, and not reload the proxy.
=> Reload the hub and proxy separately in the playbook

docs/install/https.rst
Fixes the documentation to use the `all.yml` playbook in the "Deploying without HTTPS" section.
=> Use the all.yml playbook in the no-https command

ansible/https.yml, ansible/tljh.yml, docs/install/https.rst, docs/install/index.rst
Fixes #88.
Fixes #89.
This actually disables HTTPS by default.
The main reason for this change is to reduce friction when trying out the deployment, to not have to setup the DNS. This is useful for temporary tests.
However production setups should (must) still enable HTTPS.
=> Add https.yml playbook to enable HTTPS

tljh-plasmabio/tljh_plasmabio/templates/images.html
Fixes #99.
Keeping the possibility to enter decimal values for users who really want to, or when running on a small server.
=> Set step and min values to 1 for the mem and cpu limits

ansible/admins.yml, ansible/tljh.yml, docs/environments/index.rst, docs/install/admins.rst, docs/install/ansible.rst, docs/install/index.rst
Fixes #109 
Usage: 
```bash
ansible-playbook admins.yml -i hosts -u ubuntu --extra-vars '{"admins": ["foo", bar"]}'
```
Unfortunately this task is not idempotent. `tljh-config add-item` will append the username to the list of admins even if it's already there (which makes sense for lists).
Ideally TLJH would support using `tljh-config set users.admin ["foo", "bar"]` with a list as a value, which would replace the whole list at once.
=> Add playbook to add admin users

ansible/tljh.yml
Fixes #53 
Add a check before updating the TLJH plugin in the `tljh.yml` playbook.
This also makes it easier to catch potential errors during the update of the plugin instead of ignoring them.
On a fresh run the output will look like this:
```
TASK [Check if the tljh-plasmabio is already installed] *****************************************************
ok: [test.plasmabio.org]
TASK [Upgrade the tljh-plasmabio plugin first if it is already installed] ***********************************
skipping: [test.plasmabio.org]
TASK [Run the TLJH installer] *******************************************************************************
```
For an update / rerun:
```
TASK [Check if the tljh-plasmabio is already installed] *****************************************************
ok: [test.plasmabio.org] …
```
=> Add a check before updating the TLJH plugin

docs/contributing/local.rst
Add a section about pulling `jupyter/repo2docker` in the contributing documentation.
It is needed to build images locally.
=> Add section about pulling repo2docker in contributing docs

ansible/admins.yml, ansible/https.yml, docs/install/admins.rst
Fixes #112.
This makes it possible to re-run the playbooks multiple times without adding new entries to the list.
Instructions to run the playbooks are still the same as before.
=> Unset HTTPS and admins before adding the new items

.gitignore, ansible/site.yml, ansible/users.yml, docs/install/admins.rst, docs/install/index.rst, docs/install/users.rst
Fixes #120. 
Add documentation to create users on the host using an Ansible playbook.
=> Add section about user creation to the docs

tljh-plasmabio/tljh_plasmabio/entrypoint/entrypoint.sh
The `.cache` folder comes for the base image and can be a couple of hundreds of MB big.
=> Remove the .cache folder if it exists

ansible/cockpit.yml, ansible/site.yml, docs/configuration/monitoring.rst, tljh-plasmabio/tljh_plasmabio/__init__.py
Fixes #137. 
However since Cockpit is added to the list of services in the TLJH plugin, it would probably make sense to have it installed by default:
https://github.com/plasmabio/plasmabio/blob/1ac4deb897ae5d76099afc072bf7092954de9ef9/tljh-plasmabio/tljh_plasmabio/__init__.py#L131
Otherwise the plugin could check whether the cockpit service is active before adding itself to the list of the service, using TLJH's [check_service_active](https://github.com/jupyterhub/the-littlest-jupyterhub/blob/01ba34857dd4e316d839034ae2b3cc400b929964/tljh/systemd.py#L99).
=> Update the documentation to install cockpit manually

docs/install/ansible.rst
Add a small section in the documentation to use a specific version of the Plasma plugin:
=> Add section in the documentation about git tags

ansible/docker.yml
Fixes #163.
Use the `ansible_distribution_release` variable to install Docker CE.
=> Use ansible_distribution_release to install Docker

ansible/cockpit.yml
Fixes #128. 
Add the `eoan-backports` repository to install `cockpit-docker` on Ubuntu 20.04:
https://packages.ubuntu.com/eoan-backports/all/cockpit-docker/download
=> Add eoan-backports repo for cockpit-docker

ansible/quotas.yml, ansible/users.yml, docs/install/users.rst, tljh-plasma/tljh_plasma/__init__.py
- Create ansible task to print out mounted disk on hosts
- Allow more flexibility for disk name and path on hosts
- Use 2 new Ansible variables
This should fix #138
=> Print mounted disk from Ansible task, make home dir configurable

docs/install/ansible.rst, docs/install/https.rst
Fix #175 
Documentation [Deploying with Ansible](https://docs.plasmabio.org/en/latest/install/ansible.html) is also modified:
- The case of multiple servers is addressed.
- The command line to use a single server from a multiple server `hosts` file is  provided:
```
ansible-playbook site.yml -i hosts -u ubuntu --limit server1
```
=> Unify hosts format along the doc

tljh-plasma/tljh_plasma/__init__.py
Fix #181 
Tested with success on a VM. Within an environment, user is in `/path/to/home/user/env-name` that matches the real path on the system.
@jtpio thank you for your guidance. Could please do an extra check since the Docker configuration is crucial in Plasma?
=> Match user home dir in container with system

.github/workflows/test.yml, .readthedocs.yml, ansible/tljh.yml, dev-requirements.txt, docs/conf.py, docs/contributing/local.rst, docs/index.rst, tljh-plasma/setup.py, tljh-plasma/tljh_plasma/permissions.py
=> Update to the new `repo2docker` image

tljh-plasma/tljh_plasma/__init__.py
This should fix https://github.com/plasmabio/plasma/issues/191
This new parameter corresponds to `--init` documented here: https://docs.docker.com/engine/reference/commandline/run/#options
This adds a new process as PID 1 in the Docker container:
=> Add init to extra_host_config

dev-requirements.txt, tljh-plasma/setup.py
Fixes https://github.com/plasmabio/plasma/issues/218.
Some transitive dependencies got newer major versions since the last time the repo was updated.
=> Pin `sqlalchemy<2`

.github/workflows/docs.yml, .github/workflows/test.yml
=> Minor CI maintenance

.github/workflows/test.yml, .gitignore, ansible/cockpit.yml, ansible/docker.yml, ansible/tljh.yml, ansible/vars/default.yml, dev-requirements.txt, docs/index.md, docs/install/requirements.md, docs/overview/index.md, pytest.ini, tljh-plasma/setup.py, tljh-plasma/tljh_plasma/__init__.py, tljh-plasma/tljh_plasma/entrypoint/entrypoint.sh, tljh-plasma/tljh_plasma/permissions.py, tljh-plasma/tljh_plasma/tests/conftest.py
Trying to perform a more minimal update than https://github.com/plasmabio/plasma/pull/224, as https://github.com/plasmabio/plasma/pull/224 requires more work to be fully working.
Fixes https://github.com/plasmabio/plasma/issues/227
> [!NOTE]
> The most relevant change from this update to fix #227 is the bump to `tljh-repo2docker==1.0.2` which includes https://github.com/plasmabio/tljh-repo2docker/pull/103.
> But since `tljh-repo2docker==1.0.2` also updated to JupyterHub 4, this PR updates to TLJH 1.0 (based on JupyterHub 4)
Testing with https://github.com/plasmabio/template-python/pull/13 which updates to JupyterHub 4
=> Update to TLJH 1.0, `tljh-repo2docker==1.0.2`, Ubuntu 24.04
